Resources: 
  webserver: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-7c87d913
      InstanceType: t2.micro
        UserData:
          Fn::Base64:
            !Sub:  |
            #!/bin/bash -eux
            yum install -y aws-cfn-bootstrap
            /opt/aws/bin/cfn-init -r webserver -s ${AWS::StackId} --region ${AWS::Region} -v
